# Generated by Django 3.0.6 on 2020-05-16 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('isSeller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=uuid.UUID('d7b2e0e8-3128-464f-a789-ad93e2ce20b0'), max_length=100, primary_key=True, serialize=False, unique=True)),
                ('expireAt', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
