# Generated by Django 3.0.6 on 2020-05-17 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('d6a07931-10cd-49e2-bbb4-edb529cab0eb'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
