# Generated by Django 3.0.6 on 2020-05-21 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200517_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('d6788689-26f1-44dc-81f2-b6222b038438'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
