# Generated by Django 3.0.6 on 2020-05-21 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200521_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('d789fe71-0456-4f65-8800-0107bc1cb6e4'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
