# Generated by Django 3.0.6 on 2020-05-27 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200521_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isSeller',
            new_name='is_seller',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('9656958a-a47d-4e20-94ff-5558c6a14e0c'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
