# Generated by Django 3.0.6 on 2020-05-27 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200527_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('f8c62297-e358-4eb0-91a4-3a063b6c6be2'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
