# Generated by Django 3.0.6 on 2020-05-30 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200527_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('18f03177-0a55-4322-931e-b42a92b7e837'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
