# Generated by Django 3.0.6 on 2020-05-30 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200530_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('a1fcddc1-1cf1-44a2-b8dd-6af6cd3fad83'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
