# Generated by Django 3.0.6 on 2020-06-02 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200530_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('68d7eaaf-c0a9-4629-9909-096f1de2d494'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
