# Generated by Django 3.0.6 on 2020-06-18 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200615_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='사용자', max_length=128),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(default=uuid.UUID('45d79912-464e-458c-baf3-934516b7e785'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
