# Generated by Django 3.0.7 on 2020-08-25 02:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200707_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
