# Generated by Django 3.0.7 on 2020-09-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='_password',
        ),
    ]
