# Generated by Django 3.0.6 on 2020-05-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
    ]
