# Generated by Django 3.0.6 on 2020-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200602_0926'),
        ('store', '0003_remove_store_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='registerer',
        ),
        migrations.AddField(
            model_name='store',
            name='registerer',
            field=models.ManyToManyField(to='account.User'),
        ),
    ]
