# Generated by Django 3.0.6 on 2020-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200615_1116'),
        ('store', '0004_auto_20200602_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='registered_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='registerer',
            field=models.ManyToManyField(null=True, to='account.User'),
        ),
    ]
