# Generated by Django 3.0.7 on 2020-07-07 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ian',
            field=models.CharField(default=uuid.UUID('e5dcfcec-ff90-4b31-9a8c-cb57b9475649'), max_length=36),
        ),
    ]
