# Generated by Django 3.0.7 on 2020-07-07 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200707_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ian',
            field=models.CharField(default=uuid.UUID('99fb8229-df79-48fc-88f7-b97d6c2f33c9'), max_length=36),
        ),
    ]
