# Generated by Django 3.0.7 on 2020-07-07 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200707_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ian',
            field=models.CharField(default=uuid.UUID('b5f647e5-23da-4794-81d6-a2a5f1e18476'), max_length=36),
        ),
    ]
