# Generated by Django 3.0.7 on 2020-07-07 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200707_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ian',
            field=models.CharField(default=uuid.UUID('5ebac4ab-8883-449d-8d33-57c05be67693'), max_length=36),
        ),
    ]
