# Generated by Django 3.0.7 on 2020-07-08 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200707_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ian',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
