# Generated by Django 3.0.7 on 2020-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200708_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('baby', 'Baby'), ('food', 'Food'), ('kitchen', 'Kitchen'), ('living', 'Living'), ('furniture', 'Furniture'), ('digital', 'Digital'), ('leisure', 'Leisure'), ('car', 'Car'), ('publication', 'Publication'), ('toy', 'Toy'), ('office', 'Office'), ('pet', 'Pet'), ('health', 'Health')], default='food', max_length=32),
        ),
    ]
