# Generated by Django 3.0.7 on 2020-07-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_auto_20200618_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedStock',
            fields=[
                ('osid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=16)),
                ('stocks', models.ManyToManyField(to='purchase.OrderedStock')),
            ],
        ),
    ]
