# Generated by Django 3.0.7 on 2020-08-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20200709_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedstock',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Prepared'), (1, 'Applied'), (2, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='partialorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('done', 'Done')], default='pending', max_length=16),
        ),
    ]
