# Generated by Django 3.0.7 on 2020-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='is_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
