# Generated by Django 3.0.7 on 2020-08-25 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_order_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='partialorder',
            name='is_delivery',
        ),
        migrations.AddField(
            model_name='partialorder',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
