# Generated by Django 3.0.7 on 2020-08-30 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_partialorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exclude',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='partialorder',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
