# Generated by Django 3.0.7 on 2020-08-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20200830_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
