# Generated by Django 3.0.7 on 2020-09-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_is_seller'),
        ('purchase', '0014_auto_20200830_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User'),
        ),
    ]
