# Generated by Django 3.0.7 on 2020-09-07 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_partialorder_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialorder',
            name='transport_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
