# Generated by Django 3.0.7 on 2020-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_partialorder_transport_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialorder',
            name='transport_token',
            field=models.UUIDField(null=True),
        ),
    ]
